package com.demo.entity;

public enum NotificationType {
    PAY_LATER_REQUESTED,
    CREDIT_APPROVED,
    CREDIT_REJECTED,
    PAY_LATER_REMINDER,
    ORDER_APPROVED,
    IN_PRODUCTION,
    DISPATCH_SCHEDULED,
    VEHICLE_ASSIGNED,
    DELIVERY_STATUS_UPDATED,
    ORDER_DELIVERED,
    ORDER_RETURNED
}
