package com.demo.entity;

public enum NotificationType {
    PAY_LATER_REQUESTED,
    CREDIT_APPROVED,
    CREDIT_REJECTED,
    PAY_LATER_REMINDER,
    NEW_QUOTATION_REQUEST,
    QUOTATION_REQUEST_SENT,
    QUOTATION_REQUEST_APPROVED,
    QUOTATION_SENT,
    QUOTATION_RESPONSE_ACCEPTED,
    QUOTATION_RESPONSE_REJECTED,
    ORDER_APPROVED,
    IN_PRODUCTION,
    DISPATCH_SCHEDULED,
    VEHICLE_ASSIGNED,
    DELIVERY_STATUS_UPDATED,
    ORDER_DELIVERED,
    ORDER_RETURNED
}
